### ISSUE TITLE
Getting error while executing 'bundle exec rails g spree_installments:install'

### ISSUE THREAD

**Issue by paras-ziggletech** [MisinformedDNA/spree_installments#2]
Getting error while executing 'bundle exec rails g spree_installments:install'

Called from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.0/bundler/gems/spree_installments-440ac186a187/config/initializers/spree.rb:1:in `<top (required)>': undefined method `<<' for nil:NilClass (NoMethodError)

**Comment by MisinformedDNA** [comment]
I'm not working on this code anymore. Feel free to send a PR if you figure it out.
